name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # docker push

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: lowercaseGithubRepository
      run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.lowercaseGithubRepository.outputs.repository }}/kanister-tools:latest
            ghcr.io/${{ steps.lowercaseGithubRepository.outputs.repository }}/kanister-tools:${{ github.run_number }}
        
